### ISSUE TITLE
Remove component-specific CSS-vars

### ISSUE THREAD

**Issue by amje** [gravity-ui/uikit#1007]
There are a lot of components that define CSS "API" via variables. It leads to confusion with our public CSS themes api and should be refactored. Also there is no difference in naming between variables for internal usage and public ones. 

How it works now:
```scss
.list {
  --yc-list-height: 100px; // <-- "public" local variable
  --yc-list-margin: 5px; // <-- "public" global variable
  --yc-list-size: 10px; // <-- internal usage only
]
```

How it will work in the future:
```jsx
<List height={100}/> // <-- public local CSS variable becomes a prop
```

```scss
// my-theme.scss
.yc-root {
  --yc-list-margin: 5px // <-- public global variable should be defined in the theme
}

// List.scss
.yc-list {
  --_--size: 10px; // <-- internal usage only
]
```
