### ISSUE TITLE
Respect `hidden` html attribute

### ISSUE THREAD

**Issue by vladimir-kuba** [gravity-ui/uikit#2215]
### Description

I expected the `hidden` attribute to work as described in the MDN article [The hidden state](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/hidden#the_hidden_state).

<img width="649" alt="Image" src="https://github.com/user-attachments/assets/ba102927-9375-4882-8a5d-511e42302451" />

`@gravity-ui/uikit` allows me to pass the `hidden` prop, i.e. in the [Box](https://github.com/gravity-ui/uikit/blob/9b848383f4134a8b5434ccd6812309637c00a303/src/components/layout/Box/Box.tsx#L14), but then it is overrwitten using its own styles.

<img width="396" alt="Image" src="https://github.com/user-attachments/assets/b8be8f8e-d995-4f1d-bebd-e69d5027a78b" />

This does not seem very convenient, since the user of the component has to write the ternary operator himself or use a custom style to hide the element in the DOM.

### Suggested solution

```css
/* in `styles/styles.scss` add the next lines */
.g-root[hidden], .g-root [hidden] {
  display: none;
}
```

### Validations

- [x] Check that there isn't [already an issue](https://github.com/gravity-ui/uikit/issues) that request the same feature to avoid creating a duplicate.

**Comment by vladimir-kuba** [comment]
### Alertnative

Without increasing selector specificity:

```css
/* in `styles/styles.scss` add the next lines */
:where(.g-root)[hidden], :where(.g-root) [hidden] {
  display: none;
}
```
